language: python
sudo: required
dist: trusty
group: deprecated-2017Q4
cache:
- directories:
  - "$HOME/emacs"
matrix:
  fast_finish: true
  allow_failures:
  - env: EVM_EMACS=emacs-26.1-travis
  - env: EVM_EMACS=emacs-git-snapshot-travis
env:
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-26.1-travis
  - EVM_EMACS=emacs-git-snapshot-travis
before_install:
- export PATH="$HOME/bin:$PATH"
- wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
- make -f emacs-travis.mk install_emacs
- make -f emacs-travis.mk install_cask
- emacs --version
- cask exec emacs --version
- git clone --depth 1 https://github.com/citation-style-language/test-suite.git test/suite
- git clone --depth 1 https://github.com/citation-style-language/locales.git test/locales
install:
- cask install --verbose
script:
- cask build 2>&1 | tee build.log
# - sh -c "! grep -oe '.*:Warning:.*' build.log"
- cask exec ert-runner test/citeproc-test.el
